//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todolist._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tache
    {
        public int ID { get; set; }
        public string Nom_de_l_élément { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> Est_terminé { get; set; }
    }
}
